apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ejie-corp
  description: The Ejie-corp organization
  links:
    - url: https://www.ejie.euskadi.eus/webejie00-home/es
      title: Website
spec:
  type: organization
  profile:
    displayName: Ejie 
    email: ejie@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [it]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-group
  description: A Backstage example group
spec:
  targets:
    - ./it-dept.yaml
    - ./dev-dept.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
